### ISSUE TITLE
Equation references

### ISSUE THREAD

**Issue by fiskrt** [zhihanyang2022/pytorch-a2c#1]
Where is "equation 5" that you are you referring to defined?
https://github.com/zhihanyang2022/pytorch-a2c/blob/ae940aeb36bb80b9a254e405c5d23a2ce819a88d/params_pool.py#L82

Thanks!

**Comment by ibrahimth** [comment]
Hi, 
Could you please tell me how to reference this code? Is it related to a specific paper or should we refer to this paper https://arxiv.org/pdf/1806.05635.pdf?

**Comment by zhihanyang2022** [comment]
@fiskrt @ibrahimth To both of your questions: I'm indeed referring to self imitation learning paper https://arxiv.org/pdf/1806.05635.pdf
